# Generated by Django 4.1.7 on 2023-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230201_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent Bness', 'URGENT BNESS'), ('fixing this today', 'FIXING THIS TODAY'), ('this can wait', 'THIS CAN WAIT')], default='Urgent Bness', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
