# Generated by Django 4.1.7 on 2023-04-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_priority_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent Business', 'URGENT BUSINESS'), ('fixing this today', 'FIXING THIS TODAY'), ('this can wait', 'THIS CAN WAIT')], default='Urgent Business', max_length=50, null=True),
        ),
    ]
